<h1>2. fáza - predspracovanie dát</h1>

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from sklearn.preprocessing import Imputer
from sklearn import linear_model

import re

percentil5 = []
percentil95 = []

imp = Imputer(missing_values='NaN', strategy='median')

linearKurtOx = linear_model.LinearRegression()
linearMeanGlu = linear_model.LinearRegression()

C:\Users\adria\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [2]:
def splitPersonalInfo(dataO):
    temp = dataO['personal_info'].str.split("\r\r\n|--|\\|", expand = True)
    dataO['ethn'] = temp[0]
    dataO['state'] = temp[1]
    dataO['edu'] = temp[2]
    dataO['status'] = temp[3]
    dataO['fam_memb'] = temp[4] 
    dataO.drop(['personal_info'], axis = 1, inplace = True)

In [3]:
def fusionDuplicates(datasetO):
    duplicat = datasetO[datasetO['name'].duplicated(keep=False)]
    duplicat = duplicat.sort_values('name')
    duplicat = duplicat.reset_index(drop=True)
    
    for i, row in duplicat.iterrows():
        if(i%2==1):
            duplicat = duplicat.drop(i)
            continue
        for j, value in row.items():
            dupValue = duplicat.loc[i+1,j]
            if(pd.isna(value)):
                duplicat.loc[i,j]=dupValue
    datasetO.drop_duplicates(subset='name',keep=False,inplace=True)
    result = datasetO.append(duplicat, ignore_index=True)
    return(result)

In [4]:
def correctValuesO(dataset):
    for col in dataset.columns:
        if(dataset[col].dtype != np.object):
            continue
        dataset[col] = dataset[col].str.replace('_','-')
        dataset[col] = dataset[col].replace(to_replace = r'.*\?.*', value = np.nan, regex = True)
        dataset[col] = dataset[col].replace(to_replace = r'^[Nn][Aa][Nn]$', value = np.nan, regex = True)
        if(col=='pregnant'):
            dataset[col] = dataset[col].replace(['T','F'], ['t', 'f'])
            dataset[col] = dataset[col].replace(to_replace = r'[Tt][Rr][Uu][Ee]', value = 't', regex = True)
            dataset[col] = dataset[col].replace(to_replace = r'[Ff][Aa][Ll][Ss][Ee]', value = 'f', regex = True)

def correctDates(series):
    s = series.str.split("-", expand = True)
    x = 0
    while(x<len(series)):
#        print(str(x)+" "+s.iloc[x])
        if(re.match(r'^[0-9][0-9]-[0-9][0-9]-[0-9][0-9]$', series.loc[x])):
            if(s.iloc[x][0][:1]=='0'):
                series.loc[x] = "20"+s.iloc[x][0]+"-"+s.iloc[x][1]+"-"+s.iloc[x][2][0:2]
            else:
                series.loc[x] = "19"+s.iloc[x][0]+"-"+s.iloc[x][1]+"-"+s.iloc[x][2][0:2]
#            x += 1
#            continue
         #if(len(s.iloc[x][2])>2):
         #   series.loc[x] = s.iloc[x][0]+"-"+s.iloc[x][1]+"-"+s.iloc[x][2][:2]
        if(re.match(r'^[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]$', series.loc[x])):
            y = s.iloc[x][0]
            s.iloc[x][0] = s.iloc[x][2]
            s.iloc[x][2] = y
            series.loc[x] = s.iloc[x][0]+"-"+s.iloc[x][1]+"-"+s.iloc[x][2][0:2]
        if(len(series.loc[x])>10):
            series.loc[x] = series.loc[x][0:10]
        x += 1
        
def correctValuesP(dataset):
    for col in dataset.columns:
        if(dataset[col].dtype != np.object):
            continue
        dataset[col] = dataset[col].str.replace('/','-')    
    correctDates(dataset["date_of_birth"])

In [5]:
def fusionDatasets(dataset1, dataset2):
    newDS = dataset1.merge(dataset2, on='name')
    newDS = newDS.drop(columns=['name', 'address_x', 'address_y'])
    return newDS

In [6]:
def correctAge(dataF):
    x = 0
    for x in range(len(dataF)):
        #print(x)
        s = dataF['date_of_birth'].iloc[x].split('-', 2)
        year = s[0]
        #116 najstarsi clovek v sucastnosti
        if(dataF['age'].iloc[x]>116):
            age = dataF['age'].iloc[x]/100
            if((2019-int(age) == int(year) or (2019-int(age) == int(year)+1))):
                dataF['age'].iloc[x] =  int(age);
                continue
            else:
                print("ERROR  "+str(age)+"  "+str(int(year)))
        elif(dataF['age'].iloc[x]<-116):
            age = dataF['age'].iloc[x]/(-100)
            if(2019-int(age) == int(year) or 2019-int(age) == int(year)+1):
                dataF['age'].iloc[x] =  int(age);
                continue
            else:
                print("ERROR  "+str(age)+"  "+str(int(year)))
        else:
            age = 2019 - int(year)
            if(age<=0):
                dataF['age'].iloc[x] = np.nan
            else:
                dataF['age'].iloc[x] =  int(age);

In [7]:
def detectReplaceOutliers(dataF):
    for col in dataF.columns:
        if(dataF[col].dtype == np.object):
            continue
        if(col == 'capital-loss' or col == 'capital-gain' or col == 'age'):
            continue
        if(col != 'std_glucose' and col != 'fnlwgt' and col != 'mean_glucose' and col != 'hours-per-week'):
            dataF.loc[:,col] = dataF[col].apply(lambda x: -2.5 if x<-2.5 else x)
            dataF.loc[:,col] = pd.Series(np.log(dataF[col]+2.5))
        percentil5.append(dataF[col].quantile(0.05))
        percentil95.append(dataF[col].quantile(0.95))
        p5 = percentil5[-1]
        p95 = percentil95[-1]
        print(col+" q0.05: "+str(p5))
        print(col+" q0.95: "+str(p95))
        dataF.loc[:,col] = dataF[col].apply(lambda x: p5 if x<p5 else x)
        dataF.loc[:,col] = dataF[col].apply(lambda x: p95 if x>p95 else x)

Z predchádzajúcej analýzy sme zistili, že stlpce std_glucose, fnlwgt, mean_glucose, hours-per-week majú približne normalné rozdelenie a ostatné stľpce bude potrebné transformovať pomocou logaritmu. Ten nemôže byť zo záporného čísla, preto použijeme minimálnu hodnotu z analýzi (-1.976976) a k dátam bude pre istotu prirítané 2,5. Zároveň aj ošetríme aby ani v testovacých dátach nebola nižšia hodnota tak, že všetky nižšie prestavíme na túto hodnotu.

In [8]:
def transformDetectReplaceOutliers(dataF):
    i = 0
    for col in dataF.columns:
        if(dataF[col].dtype == np.object):
            continue
        if(col == 'capital-loss' or col == 'capital-gain' or col == 'age'):
            continue
        if(col != 'std_glucose' and col != 'fnlwgt' and col != 'mean_glucose' and col != 'hours-per-week'):
            dataF.loc[:,col] = dataF[col].apply(lambda x: -2.5 if x<-2.5 else x)
            dataF.loc[:,col] = pd.Series(np.log(dataF[col]+2.5))
        p5 = percentil5[i]
        p95 = percentil95[i]
        i=i+1
        print(col+" q0.05: "+str(p5))
        print(col+" q0.95: "+str(p95))
        dataF.loc[:,col] = dataF[col].apply(lambda x: p5 if x<p5 else x)
        dataF.loc[:,col] = dataF[col].apply(lambda x: p95 if x>p95 else x)

In [9]:
def impMedianFit(dataF):
    imp.fit(dataF[["age","skewness_glucose","std_oxygen", "capital-gain", "skewness_oxygen", "kurtosis_glucose", "fnlwgt", "std_glucose", "mean_oxygen", "hours-per-week", "capital-loss"]])
    
def impMedianTransform(dataF):
    dataF[["age","skewness_glucose","std_oxygen", "capital-gain", "skewness_oxygen", "kurtosis_glucose", "fnlwgt", "std_glucose", "mean_oxygen", "hours-per-week", "capital-loss"]] = imp.transform(dataF[["age","skewness_glucose","std_oxygen", "capital-gain", "skewness_oxygen", "kurtosis_glucose", "fnlwgt", "std_glucose", "mean_oxygen", "hours-per-week", "capital-loss"]])

In [10]:
def linearFit(dataF):
    dataToFit = dataF[~dataF["kurtosis_oxygen"].isnull()]
    linearKurtOx.fit(X = dataToFit[["skewness_oxygen","mean_oxygen"]], y = dataF["kurtosis_oxygen"].dropna())
    dataToFit = dataF[~dataF["mean_glucose"].isnull()]
    linearMeanGlu.fit(X = dataToFit[["skewness_glucose", "kurtosis_glucose"]], y = dataF["mean_glucose"].dropna())
def linearTransform(dataF):
    dataF.loc[dataF["kurtosis_oxygen"].isnull(), "kurtosis_oxygen"] = linearKurtOx.predict(dataF[["skewness_oxygen","mean_oxygen"]])[dataF["kurtosis_oxygen"].isnull()]
    dataF.loc[dataF["mean_glucose"].isnull(), "mean_glucose"] = linearMeanGlu.predict(dataF[["skewness_glucose", "kurtosis_glucose"]])[dataF["mean_glucose"].isnull()]

In [11]:
def setKategNaNtoUnknown(dataF):
    for col in dataF.columns:
        if(dataF[col].dtype != np.object):
            continue
        dataF[col].replace(to_replace=np.nan, value='unknown', inplace = True)

In [12]:
def finalFitAndTransform(dataP,dataO):
    print('spliting personal info')
    splitPersonalInfo(dataO)
    print('deduplicating names')
    dataO=fusionDuplicates(dataO)
    print('correcting O values')
    correctValuesO(dataO)
    print('correcting P values')
    correctValuesP(dataP)
    print('merging datasets')
    dataF = fusionDatasets(dataP, dataO)
    dataF = dataF.astype({'class':str,"education-num":str,"kurtosis_oxygen":float})
    
    print('correcting age')
    correctAge(dataF)
    print('correcting outliers')
    detectReplaceOutliers(dataF)
    
    setKategNaNtoUnknown(dataF)
    print('filling missing values with median')
    impMedianFit(dataF)
    impMedianTransform(dataF)
    print('filling missing values with linear regression')
    linearFit(dataF)
    linearTransform(dataF)
    return dataF

In [13]:
def finalTransform(dataP,dataO):
    print('correcting values')
    splitPersonalInfo(dataO)
    dataO=fusionDuplicates(dataO)
    correctValuesO(dataO)
    correctValuesP(dataP)
    dataF = fusionDatasets(dataP, dataO)
    dataF = dataF.astype({'class':str,"education-num":str,"kurtosis_oxygen":float})
    print('working with outliers')
    correctAge(dataF)
    transformDetectReplaceOutliers(dataF)
    print('filling missing values')
    setKategNaNtoUnknown(dataF)
    impMedianTransform(dataF)
    linearTransform(dataF)
    return dataF

In [14]:
dataP = pd.read_csv("personal_train.csv", index_col=0)
dataO = pd.read_csv("other_train.csv", index_col=0)

In [15]:
splitPersonalInfo(dataO)

Zozdelenie stípca personal info z analýzy.

In [16]:
dataP.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3933 entries, 0 to 3932
Data columns (total 5 columns):
name             3933 non-null object
address          3933 non-null object
age              3933 non-null int64
sex              3933 non-null object
date_of_birth    3933 non-null object
dtypes: int64(1), object(4)
memory usage: 184.4+ KB

In [17]:
dataO.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3983 entries, 0 to 3982
Data columns (total 25 columns):
name                3983 non-null object
address             3983 non-null object
kurtosis_oxygen     3709 non-null object
occupation          3974 non-null object
pregnant            3967 non-null object
education-num       3964 non-null float64
skewness_glucose    3970 non-null float64
mean_glucose        3573 non-null float64
std_oxygen          3967 non-null float64
capital-gain        3970 non-null float64
skewness_oxygen     3969 non-null float64
kurtosis_glucose    3965 non-null float64
fnlwgt              3974 non-null float64
class               3972 non-null float64
std_glucose         3964 non-null float64
income              3967 non-null object
mean_oxygen         3971 non-null float64
hours-per-week      3969 non-null float64
capital-loss        3971 non-null float64
workclass           3961 non-null object
ethn                3968 non-null object
state               3968 non-null object
edu                 3968 non-null object
status              3968 non-null object
fam_memb            3968 non-null object
dtypes: float64(13), object(12)
memory usage: 809.0+ KB

In [18]:
len(dataO.name.unique())

3933

In [19]:
namesO = dataO["name"].unique().sort()

In [20]:
namesP = dataP["name"].unique().sort()

In [21]:
np.array_equal(namesO, namesP)

True

Zistili sme, že mená v obydvoch datasetochsú rovnaké, preto odstraníme duplicitn mená z datasetu other.

In [22]:
duplNames = dataO[dataO['name'].duplicated(keep=False)]
duplNames.sort_values('name')

,name,address,kurtosis_oxygen,occupation,pregnant,education-num,skewness_glucose,mean_glucose,std_oxygen,capital-gain,...,income,mean_oxygen,hours-per-week,capital-loss,workclass,ethn,state,edu,status,fam_memb
3718,Andrew Lawson,57159 Christopher Throughway Apt. 388\r\nWest ...,10.56049223,NaN,f,NaN,2.486716,87.585938,16.756233,0.0,...,>50K,2.035117,40.0,0.0,NaN,White,United-States,Bachelors,Married-civ-spouse,Husband
1298,Andrew Lawson,57159 Christopher Throughway Apt. 388\r\nWest ...,10.56049223,Sales,f,13.0,2.486716,87.585938,16.756233,NaN,...,NaN,2.035117,40.0,0.0,Private,White,United-States,Bachelors,Married-civ-spouse,Husband
3402,Andrew Olmstead,"519 Christopher Loop Suite 282\r\nRachelside, ...",6.9289193560000015,Craft-repair,f,9.0,0.548669,NaN,26.559749,0.0,...,<=50K,4.382943,52.0,0.0,NaN,White,United-States,HS-grad,Married-civ-spouse,Husband
281,Andrew Olmstead,"519 Christopher Loop Suite 282\r\nRachelside, ...",6.9289193560000015,NaN,f,NaN,0.548669,NaN,26.559749,0.0,...,<=50K,4.382943,52.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
3851,Antonio Bailey,"29028 Bowman Parkways\r\nKerrview, FL 57851",0.368701087,Sales,f,6.0,10.093518,57.312500,79.734804,0.0,...,<=50K,96.128763,40.0,NaN,Self-emp-inc,White,Canada,10th,Widowed,Unmarried
2222,Antonio Bailey,"29028 Bowman Parkways\r\nKerrview, FL 57851",0.368701087,Sales,NaN,NaN,10.093518,57.312500,79.734804,NaN,...,<=50K,NaN,40.0,0.0,Self-emp-inc,White,Canada,10th,Widowed,Unmarried
2606,Antonio Rowan,"016 Jacob Tunnel Apt. 031\r\nAmandabury, CA 37683",??,Handlers-cleaners,f,9.0,0.208850,128.968750,15.056887,0.0,...,NaN,1.887960,45.0,0.0,Private,NaN,NaN,NaN,NaN,NaN
1987,Antonio Rowan,"016 Jacob Tunnel Apt. 031\r\nAmandabury, CA 37683",??,Handlers-cleaners,NaN,9.0,0.208850,128.968750,15.056887,0.0,...,<=50K,1.887960,45.0,0.0,Private,Black,United-States,HS-grad,Separated,Unmarried
3947,Ben Nelson,"45315 Obrien Inlet\r\nCynthiaport, OH 63603",22.14937084,Transport-moving,f,9.0,1.137467,92.804688,9.089983,0.0,...,>50K,0.511706,40.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
956,Ben Nelson,"45315 Obrien Inlet\r\nCynthiaport, OH 63603",22.14937084,Transport-moving,f,9.0,NaN,NaN,NaN,0.0,...,>50K,0.511706,40.0,0.0,Private,NaN,NaN,NaN,NaN,NaN
3274,Charles Pollack,"5703 Wilson Union Apt. 105\r\nStevenhaven, NJ ...",2.3511303530000003,Exec-managerial,t,11.0,1.789749,105.523438,55.529609,0.0,...,NaN,23.042642,NaN,0.0,Private,White,United-States,Assoc-voc,Divorced,Unmarried
3024,Charles Pollack,"5703 Wilson Union Apt. 105\r\nStevenhaven, NJ ...",2.3511303530000003,Exec-managerial,t,NaN,1.789749,105.523438,55.529609,0.0,...,NaN,23.042642,45.0,0.0,Private,White,United-States,Assoc-voc,Divorced,Unmarried
918,Craig Solomon,"PSC 7142, Box 7999\r\nAPO AA 51659",9.046560192000001,Sales,f,10.0,0.191146,NaN,15.941463,NaN,...,<=50K,NaN,22.0,0.0,NaN,White,United-States,Some-college,Never-married,Own-child
6,Craig Solomon,"PSC 7142, Box 7999\r\nAPO AA 51659",9.046560192000001,Sales,f,10.0,0.191146,NaN,15.941463,0.0,...,<=50K,2.176421,NaN,0.0,Private,White,United-States,Some-college,Never-married,Own-child
2340,David Arebalo,"0519 Cassie Orchard\r\nNew John, TX 71955",1.28418567,Exec-managerial,f,10.0,-0.201500,124.132812,80.684349,NaN,...,>50K,45.673077,50.0,0.0,Private,White,United-States,Some-college,Married-civ-spouse,Husband
1791,David Arebalo,"0519 Cassie Orchard\r\nNew John, TX 71955",1.28418567,Exec-managerial,f,NaN,-0.201500,124.132812,80.684349,0.0,...,NaN,45.673077,NaN,NaN,Private,White,United-States,Some-college,Married-civ-spouse,Husband
636,David Jones,"2455 Richardson Forks\r\nNorth Seanside, AL 57677",8.815196362,Prof-specialty,NaN,14.0,0.069518,139.898438,18.166055,0.0,...,<=50K,NaN,40.0,0.0,Local-gov,White,United-States,Masters,Married-civ-spouse,Husband
1813,David Jones,"2455 Richardson Forks\r\nNorth Seanside, AL 57677",8.815196362,Prof-specialty,f,14.0,0.069518,139.898438,18.166055,0.0,...,<=50K,2.482441,NaN,0.0,Local-gov,White,United-States,Masters,Married-civ-spouse,Husband
3878,David Short,"42574 Sutton Parkway\r\nPedromouth, OH 97593",NaN,Prof-specialty,f,14.0,30.428177,31.601562,62.868452,0.0,...,>50K,33.494983,30.0,0.0,Self-emp-not-inc,White,?,Masters,Married-civ-spouse,Husband
477,David Short,"42574 Sutton Parkway\r\nPedromouth, OH 97593",NaN,Prof-specialty,NaN,14.0,30.428177,31.601562,62.868452,0.0,...,>50K,33.494983,30.0,NaN,Self-emp-not-inc,NaN,NaN,NaN,NaN,NaN
3241,Donald Doyle,"48674 Sherry Alley Suite 529\r\nWest Nicholas,...",NaN,Sales,FALSE,NaN,NaN,111.320312,20.223886,0.0,...,NaN,2.982441,40.0,0.0,Private,NaN,NaN,NaN,NaN,NaN
174,Donald Doyle,"48674 Sherry Alley Suite 529\r\nWest Nicholas,...",NaN,Sales,FALSE,9.0,0.121351,111.320312,20.223886,0.0,...,<=50K,2.982441,40.0,NaN,Private,White,United-States,HS-grad,Never-married,Other-relative
514,Doyle Jenkins,"51959 Hawkins Stravenue\r\nWest Randy, MD 64351",2.961762332,Exec-managerial,f,13.0,0.021654,108.421875,55.631299,0.0,...,NaN,17.905518,40.0,0.0,Private,Asian-Pac-Islander,Philippines,Bachelors,Never-married,Not-in-family
2984,Doyle Jenkins,"51959 Hawkins Stravenue\r\nWest Randy, MD 64351",2.961762332,Exec-managerial,f,13.0,0.021654,108.421875,55.631299,0.0,...,<=50K,17.905518,NaN,0.0,Private,Asian-Pac-Islander,Philippines,Bachelors,Never-married,Not-in-family
2540,George Gilpatrick,"2906 Mitchell Crest Apt. 568\r\nHollyton, OH 4...",15.88535622,Farming-fishing,f,9.0,-0.544716,127.703125,12.709748,0.0,...,<=50K,1.107860,NaN,0.0,Local-gov,White,United-States,HS-grad,Never-married,Own-child
1277,George Gilpatrick,"2906 Mitchell Crest Apt. 568\r\nHollyton, OH 4...",15.88535622,Farming-fishing,NaN,9.0,-0.544716,127.703125,12.709748,0.0,...,<=50K,1.107860,20.0,NaN,Local-gov,NaN,NaN,NaN,NaN,NaN
3204,George Smith,"69758 Barnett Canyon Apt. 635\r\nVirginialand,...",8.108129205,Transport-moving,NaN,NaN,NaN,NaN,18.566882,0.0,...,<=50K,2.998328,40.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
2779,George Smith,"69758 Barnett Canyon Apt. 635\r\nVirginialand,...",8.108129205,Transport-moving,f,9.0,-0.034614,114.664062,18.566882,0.0,...,<=50K,2.998328,40.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
294,Gordon Funderburk,Unit 9139 Box 5625\r\nDPO AP 85541,4.847933096,Exec-managerial,f,9.0,-0.699649,NaN,34.186123,0.0,...,<=50K,7.177258,40.0,0.0,Local-gov,White,United-States,HS-grad,Widowed,Not-in-family
3010,Gordon Funderburk,Unit 9139 Box 5625\r\nDPO AP 85541,4.847933096,Exec-managerial,f,9.0,-0.699649,NaN,NaN,0.0,...,<=50K,NaN,40.0,0.0,NaN,White,United-States,HS-grad,Widowed,Not-in-family
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2267,Mike Murdock,"842 Scott Road\r\nWest Michael, ND 69887",NaN,Sales,NaN,13.0,-0.265510,136.914062,20.745736,NaN,...,NaN,3.691472,35.0,0.0,Private,Black,United-States,Bachelors,Never-married,Unmarried
2201,Mike Murdock,"842 Scott Road\r\nWest Michael, ND 69887",NaN,Sales,f,13.0,-0.265510,136.914062,20.745736,0.0,...,>50K,NaN,35.0,0.0,NaN,Black,United-States,Bachelors,Never-married,Unmarried
2976,Mike Rm,"8317 Sarah Streets Apt. 987\r\nWrighttown, NY ...",12.28357567,Transport-moving,f,5.0,-0.463015,117.078125,14.469198,0.0,...,>50K,1.468227,70.0,0.0,Self-emp-not-inc,White,United-States,9th,Married-civ-spouse,Husband
1554,Mike Rm,"8317 Sarah Streets Apt. 987\r\nWrighttown, NY ...",NaN,Transport-moving,f,NaN,NaN,NaN,14.469198,0.0,...,>50K,1.468227,NaN,0.0,Self-emp-not-inc,White,United-States,9th,Married-civ-spouse,Husband
3634,Paul Ladd,USNS Townsend\r\nFPO AE 97197,6.062392209,Sales,f,9.0,2.179898,94.218750,29.733092,NaN,...,NaN,5.266722,25.0,NaN,NaN,White,United-States,HS-grad,Never-married,Own-child
84,Paul Ladd,USNS Townsend\r\nFPO AE 97197,6.062392209,Sales,f,9.0,2.179898,94.218750,29.733092,0.0,...,<=50K,5.266722,25.0,0.0,Private,White,United-States,HS-grad,Never-married,Own-child
3441,Randall Mellett,"941 Woods Walks Suite 315\r\nNorth Andrealand,...",6.773794869,Sales,f,NaN,-0.104047,127.546875,NaN,NaN,...,<=50K,4.233278,45.0,0.0,Private,NaN,NaN,NaN,NaN,NaN
124,Randall Mellett,"941 Woods Walks Suite 315\r\nNorth Andrealand,...",6.773794869,Sales,f,10.0,-0.104047,127.546875,25.401128,0.0,...,<=50K,4.233278,45.0,0.0,Private,White,United-States,Some-college,Never-married,Not-in-family
1856,Raymond Goode,"0705 Heather Mountain\r\nFloresmouth, FL 91113",8.074870162,Craft_repair,f,NaN,NaN,NaN,NaN,0.0,...,<=50K,NaN,32.0,0.0,Self-emp-not-inc,White,United-States,HS-grad,Married-civ-spouse,Husband
3162,Raymond Goode,"0705 Heather Mountain\r\nFloresmouth, FL 91113",8.074870162,Craft_repair,f,9.0,1.290224,89.437500,18.902544,0.0,...,<=50K,2.625418,32.0,0.0,Self-emp-not-inc,White,United-States,HS-grad,Married-civ-spouse,Husband
826,Robert Lackey,"94782 Ortega Summit\r\nNew Andrewmouth, MN 99751",8.466196457999999,Other-service,f,9.0,NaN,NaN,17.515368,0.0,...,<=50K,2.780936,25.0,0.0,Private,White,United-States,HS-grad,Never-married,Other-relative
3785,Robert Lackey,"94782 Ortega Summit\r\nNew Andrewmouth, MN 99751",8.466196457999999,Other-service,f,9.0,0.492993,NaN,NaN,0.0,...,<=50K,2.780936,25.0,0.0,NaN,White,United-States,HS-grad,Never-married,Other-relative
1961,Russell Coleman,"PSC 1977, Box 7638\r\nAPO AE 29246",0.48443973,Sales,f,13.0,13.105819,17.023438,66.372428,0.0,...,<=50K,95.912207,NaN,0.0,Private,White,United-States,Bachelors,Never-married,Not-in-family
1874,Russell Coleman,"PSC 1977, Box 7638\r\nAPO AE 29246",0.48443973,Sales,f,13.0,13.105819,NaN,NaN,0.0,...,<=50K,95.912207,40.0,NaN,Private,White,United-States,Bachelors,Never-married,Not-in-family
2159,Salvador Donnell,"287 Jessica Springs Apt. 923\r\nSantanaton, ND...",7.151723994,Prof-specialty,FALSE,NaN,0.108239,115.875000,22.170373,0.0,...,>50K,3.521739,42.0,0.0,Private,White,United-States,Masters,Married-civ-spouse,Husband
1241,Salvador Donnell,"287 Jessica Springs Apt. 923\r\nSantanaton, ND...",7.151723994,NaN,FALSE,14.0,0.108239,115.875000,NaN,NaN,...,>50K,3.521739,42.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2978,Steven Jacobs,"84245 Williamson Trail\r\nEast Pamelaside, AL ...",6.633057813,Prof-specialty,NaN,14.0,1.477925,88.710938,NaN,0.0,...,<=50K,NaN,50.0,0.0,NaN,White,United-States,Masters,Married-civ-spouse,Husband
1921,Steven Jacobs,"84245 Williamson Trail\r\nEast Pamelaside, AL ...",6.633057813,Prof-specialty,f,14.0,1.477925,88.710938,25.308950,0.0,...,<=50K,4.444816,50.0,0.0,State-gov,White,United-States,Masters,Married-civ-spouse,Husband
2999,Tim Price,"4811 Raymond Locks Suite 069\r\nEast Michael, ...",15.36988913,Prof-specialty,NaN,13.0,NaN,125.625000,11.701942,NaN,...,>50K,1.147993,40.0,0.0,Private,White,United-States,Bachelors,Never-married,Not-in-family
3077,Tim Price,"4811 Raymond Locks Suite 069\r\nEast Michael, ...",15.36988913,Prof-specialty,t,13.0,-0.191658,125.625000,NaN,0.0,...,>50K,1.147993,40.0,NaN,Private,White,United-States,Bachelors,Never-married,Not-in-family
2818,Virgil Selman,66909 Frederick Path Apt. 504\r\nPort Jennifer...,NaN,Sales,f,7.0,-0.025640,NaN,10.809350,0.0,...,<=50K,NaN,15.0,0.0,Private,White,United-States,11th,Never-married,Own-child
3480,Virgil Selman,66909 Frederick Path Apt. 504\r\nPort Jennifer...,NaN,Sales,f,7.0,-0.025640,111.601562,10.809350,0.0,...,<=50K,1.607860,15.0,0.0,Private,White,United-States,11th,Never-married,Own-child
2474,William Glover,"655 Cody River Suite 554\r\nNorth Colton, DC 2...",NaN,Sales,f,9.0,-0.172403,138.429688,12.075740,0.0,...,<=50K,1.458194,40.0,0.0,NaN,White,United-States,HS-grad,Married-civ-spouse,Husband
2372,William Glover,"655 Cody River Suite 554\r\nNorth Colton, DC 2...",12.39898059,NaN,f,9.0,-0.172403,138.429688,12.075740,0.0,...,<=50K,1.458194,40.0,0.0,NaN,White,United-States,HS-grad,Married-civ-spouse,Husband
2423,William Hicks,"66744 Tiffany Shores Apt. 950\r\nNew Timothy, ...",2.45648463,Prof-specialty,f,14.0,31.058851,33.226562,57.705184,NaN,...,<=50K,26.705686,40.0,0.0,Federal-gov,White,United-States,Masters,Married-civ-spouse,Husband
1683,William Hicks,"66744 Tiffany Shores Apt. 950\r\nNew Timothy, ...",NaN,Prof-specialty,f,NaN,31.058851,33.226562,57.705184,0.0,...,<=50K,26.705686,40.0,0.0,NaN,White,United-States,Masters,Married-civ-spouse,Husband
2575,William Joecks,"089 Sherry Hollow Suite 058\r\nBrianberg, CT 0...",NaN,Other-service,f,NaN,-0.220297,117.601562,83.396249,0.0,...,<=50K,NaN,15.0,0.0,Private,White,United-States,11th,Never-married,Own-child
2280,William Joecks,"089 Sherry Hollow Suite 058\r\nBrianberg, CT 0...",??,Other-service,f,7.0,-0.220297,117.601562,83.396249,0.0,...,<=50K,79.782609,NaN,0.0,Private,White,United-States,11th,Never-married,Own-child
2259,William Stone,"535 Cabrera Wall Apt. 927\r\nEast David, TX 70904",NaN,Adm-clerical,f,9.0,-0.391453,118.609375,NaN,0.0,...,NaN,6.880435,35.0,0.0,Local-gov,Black,United-States,HS-grad,Divorced,Unmarried
1236,William Stone,"535 Cabrera Wall Apt. 927\r\nEast David, TX 70904",NaN,Adm-clerical,f,NaN,-0.391453,118.609375,31.452809,0.0,...,<=50K,6.880435,35.0,0.0,NaN,Black,United-States,HS-grad,Divorced,Unmarried

Po vypísani duplicitných mien sme zistili, že zlúčením týchto duplikátov vieme vyplniť chýbajúce hodnoty. Zároveň hodnoty, ktoré majú oba duplikáty sú rovnaké.

In [23]:
dataO=fusionDuplicates(dataO)
dataO

,name,address,kurtosis_oxygen,occupation,pregnant,education-num,skewness_glucose,mean_glucose,std_oxygen,capital-gain,...,income,mean_oxygen,hours-per-week,capital-loss,workclass,ethn,state,edu,status,fam_memb
0,Daniel Love,"126 Ramirez Roads\r\nNew Jayville, IL 18861",10.58036423,Sales,f,9.0,3.158830,85.859375,14.121127,0.0,...,>50K,1.857860,40.0,1902.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
1,Roy Paradis,"01168 Stark Pine Apt. 583\r\nDavidville, IN 32044",3.713364594,Craft-repair,f,9.0,1.234184,91.679688,36.946291,0.0,...,<=50K,10.001672,40.0,2002.0,Self-emp-not-inc,White,United-States,HS-grad,Married-civ-spouse,Husband
2,Charles Chen,"09482 Horne Lakes Apt. 373\r\nEast Brian, TN 2...",6.478064004,Handlers-cleaners,f,9.0,1.872355,89.960938,22.646980,0.0,...,<=50K,4.134615,48.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
3,Chester Holmes,"720 Harris Turnpike Suite 732\r\nEast Sierra, ...",??,Sales,f,10.0,0.395583,NaN,14.001759,0.0,...,>50K,1.849498,40.0,0.0,Private,White,United-States,Some-college,Married-civ-spouse,Husband
4,James Ayala,Unit 3230 Box 9523\r\nDPO AA 55810,NaN,Transport-moving,f,9.0,0.493384,94.593750,29.361953,0.0,...,<=50K,5.739130,40.0,0.0,Private,Amer-Indian-Eskimo,United-States,HS-grad,Married-civ-spouse,Husband
5,Todd Flanagan,"2167 Wells Shoals Apt. 264\r\nEast Brianshire,...",6.384963147000001,?,f,9.0,-0.303185,125.742188,29.664529,0.0,...,<=50K,4.951505,15.0,0.0,?,White,United-States,HS-grad,Married-civ-spouse,Own-child
6,James Huffman,"535 Michael Squares\r\nNorth Sara, ID 61368",8.938092965,Sales,f,10.0,0.091356,145.835938,19.440728,0.0,...,<=50K,2.637124,50.0,0.0,Private,White,United-States,Some-college,Divorced,Not-in-family
7,Gary Prentice,"055 Nolan Club\r\nWest Bryanton, UT 15308",5.155939859,?,f,12.0,0.046797,138.179688,31.576347,0.0,...,<=50K,6.330268,1.0,0.0,?,White,United-States,Assoc-acdm,Divorced,Unmarried
8,Rodger Riis,7719 Frances Drives Apt. 525\r\nWest Brandonst...,2.436555082,Sales,f,10.0,-0.797075,129.976562,56.661158,0.0,...,<=50K,22.038462,35.0,0.0,Self-emp-inc,White,United-States,Some-college,Never-married,Own-child
9,Robert Cabiness,"70838 Robbins Camp Suite 853\r\nJacobville, SC...",14.38934822,Sales,f,9.0,1.035747,107.578125,11.797305,0.0,...,<=50K,1.002508,40.0,0.0,Private,White,United-States,HS-grad,Never-married,Own-child
10,John Brehmer,"019 Donna Mountains\r\nAlyssaside, NC 78687",8.508906253,Adm-clerical,f,9.0,-0.362887,125.406250,19.298961,0.0,...,<=50K,3.076087,40.0,0.0,Federal-gov,Black,United-States,HS-grad,Separated,Unmarried
11,William West,"692 Tiffany Cape Suite 776\r\nNew Stacey, OK 9...",10.30903207,Exec-managerial,f,10.0,0.095533,117.390625,15.481005,0.0,...,>50K,2.125418,40.0,0.0,Private,White,United-States,Some-college,Married-civ-spouse,Husband
12,Thomas Rathburn,"708 Rodgers Streets Suite 909\r\nVanessamouth,...",8.620895914,Craft-repair,f,9.0,-0.685681,NaN,19.802528,0.0,...,<=50K,2.981605,40.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
13,Steven Welch,4017 Christopher Fort Suite 454\r\nHurleyville...,6.241462914,Craft-repair,f,9.0,0.440195,125.382812,33.316921,0.0,...,<=50K,5.237458,40.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
14,Leon Fleming,"2351 Brian Route Suite 878\r\nPort Richard, SC...",-0.219283809,Craft-repair,f,10.0,19.330374,35.664062,85.581283,0.0,...,>50K,126.169732,40.0,0.0,Private,White,United-States,Some-college,Divorced,Not-in-family
15,Jake Pearce,"1633 Sanders Club\r\nSouth Timothymouth, LA 30038",8.520990655,Farming-fishing,f,10.0,1.590114,110.226562,17.170471,0.0,...,<=50K,2.513378,40.0,0.0,State-gov,White,United-States,Some-college,Never-married,Own-child
16,Carl Nelson,"680 Higgins Square\r\nSharonborough, NJ 01147",10.64449998,Other-service,f,10.0,1.617376,83.812500,14.760813,0.0,...,<=50K,1.977425,40.0,0.0,Private,White,United-States,Some-college,Married-civ-spouse,Husband
17,Brian Murphrey,"7682 Cantu Glen\r\nMonroebury, NH 02629",3.870762606,Handlers-cleaners,f,9.0,0.867397,131.656250,40.512098,0.0,...,<=50K,10.780100,40.0,0.0,Private,White,United-States,HS-grad,Never-married,Not-in-family
18,Brian Orozco,"699 Powell Gardens Apt. 171\r\nSloanland, HI 6...",7.919433455,Prof-specialty,F,13.0,-0.026361,136.648438,16.939515,0.0,...,<=50K,3.082776,50.0,0.0,Private,White,United-States,Bachelors,Divorced,Not-in-family
19,Julian Davis,75930 Jonathan Passage Suite 688\r\nPort Jamie...,5.560734251,Other-service,f,10.0,-0.174616,129.171875,34.033077,0.0,...,<=50K,6.186455,40.0,0.0,Private,White,United-States,Some-college,Married-civ-spouse,Husband
20,John Davenport,802 Christian Course Apt. 645\r\nPort Dominiqu...,9.858380523,Sales,f,9.0,2.022478,83.937500,15.002609,0.0,...,<=50K,2.117057,50.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Wife
21,Oscar Reynolds,"776 Guerrero Lock\r\nLake Erin, NY 53271",12.38519299,Tech-support,f,13.0,22.614915,39.843750,11.812581,0.0,...,>50K,1.905518,40.0,0.0,Private,Asian-Pac-Islander,India,Bachelors,Married-civ-spouse,Husband
22,Louis Stallworth,"476 Kevin Tunnel\r\nJenniferton, VT 33302",12.14303861,Craft-repair,f,9.0,0.250451,117.242188,12.032379,0.0,...,<=50K,1.759197,40.0,0.0,Private,White,United-States,HS-grad,Divorced,Own-child
23,Harold Hiles,"40820 Susan Shore\r\nCoryville, KS 28888",7.012918477,Craft-repair,f,7.0,0.003438,144.554688,27.775424,0.0,...,<=50K,4.556856,36.0,0.0,Self-emp-not-inc,White,United-States,11th,Married-civ-spouse,Husband
24,David Lopez,"420 Jensen Place\r\nPort Kyletown, KS 65788",8.02251786,Prof-specialty,f,10.0,0.410473,95.882812,18.127732,0.0,...,<=50K,2.973244,40.0,0.0,Private,White,United-States,Some-college,Divorced,Unmarried
25,Kenneth Weatherholt,6644 Marshall Mountains Suite 928\r\nWest Susa...,-0.074639079,Exec-managerial,FALSE,9.0,0.092750,112.406250,85.955181,0.0,...,<=50K,90.637124,40.0,0.0,Federal-gov,Black,United-States,HS-grad,Separated,Not-in-family
26,Corey Rose,"48053 Jeremiah Estate\r\nJeremychester, TN 50588",4.62701081,Adm-clerical,t,10.0,-0.326696,115.906250,33.779169,0.0,...,<=50K,7.519231,37.0,0.0,Private,Black,United-States,Some-college,Divorced,Unmarried
27,Arthur Crandall,806 Matthews River Suite 584\r\nPort Heidiside...,0.978638555,Exec-managerial,f,11.0,26.289988,52.687500,80.095947,0.0,...,>50K,61.021739,45.0,0.0,Private,White,United-States,Assoc-voc,Divorced,Not-in-family
28,Jesse Simpson,"6825 Lopez Crest Suite 574\r\nLake Sarah, CO 6...",8.265676186,Craft-repair,f,9.0,-0.585491,125.687500,19.353314,0.0,...,<=50K,2.720736,40.0,0.0,Private,White,United-States,HS-grad,Never-married,Not-in-family
29,Rene Kershner,"1010 Miles Shore Suite 346\r\nWest Edward, NH ...",7.6771816039999985,Sales,f,9.0,-0.614574,124.039062,19.800855,0.0,...,<=50K,2.897157,40.0,0.0,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3903,Joseph Palumbo,"14921 Johnson Stravenue\r\nNorth David, KS 12153",1.582775516,Prof-specialty,FALSE,14.0,38.426350,28.195312,68.162797,0.0,...,>50K,50.848662,NaN,0.0,Local-gov,White,United-States,Masters,Married-civ-spouse,Husband
3904,Joseph Perez,"023 Cook Bypass Apt. 625\r\nNorth Anna, FL 05626",8.272507037999999,Machine_op_inspct,f,10.0,0.079527,NaN,18.194276,0.0,...,<=50K,2.710702,40.0,0.0,Private,Asian-Pac-Islander,Philippines,Some-college,Married-civ-spouse,Husband
3905,Joseph Williams,"6558 Smith Park Apt. 719\r\nLake Johnmouth, DE...",15.23249089,Craft-repair,F,10.0,0.581744,NaN,11.739069,15024.0,...,>50K,0.939799,40.0,0.0,Private,Black,United-States,Some-college,Married-civ-spouse,Husband
3906,Juan Thurber,"655 Rosales Camp Suite 191\r\nDavisview, WV 49205",0.243013429,Prof-specialty,f,14.0,27.574659,31.109375,66.434844,0.0,...,>50K,115.192308,40.0,0.0,Federal-gov,White,?,Masters,Married-civ-spouse,Husband
3907,Kenneth Burr,"61596 Danielle Trafficway\r\nSouth Ryan, ND 49582",NaN,Prof-specialty,f,14.0,1.259574,116.226562,28.590406,0.0,...,>50K,5.403846,40.0,0.0,Self-emp-not-inc,White,United-States,Masters,Married-civ-spouse,Husband
3908,Kenneth Zamora,"9086 Becker Streets\r\nNew Michaelbury, MA 54353",2.325276941,Transport-moving,f,9.0,0.519678,110.664062,58.577725,15831.0,...,>50K,22.954013,40.0,0.0,Private,White,United-States,HS-grad,Never-married,Not-in-family
3909,Kevin Bell,"793 Erika Springs Suite 802\r\nLake Donnaview,...",5.726569838,Adm_clerical,f,9.0,4.056839,83.148438,30.577686,0.0,...,<=50K,6.010033,40.0,0.0,NaN,White,United-States,HS-grad,Never-married,Own-child
3910,Leslie Pack,"77641 Brian Camp\r\nSouth Amberville, IA 89230",-1.529820477,Machine-op-inspct,f,8.0,1.953768,184.296875,77.547235,0.0,...,<=50K,174.563545,45.0,0.0,Private,White,United-States,12th,Never-married,Not-in-family
3911,Lonnie Fuhrman,"77622 Bright Station\r\nMorrismouth, MO 52269",NaN,Other-service,f,9.0,31.808962,NaN,55.135775,0.0,...,<=50K,34.369565,40.0,0.0,Private,White,United-States,HS-grad,Never-married,Other-relative
3912,Louis Lochrico,"358 Reed Springs\r\nEast Stevenport, NC 86309",8.034997045,Prof-specialty,f,15.0,0.022226,111.148438,19.402824,99999.0,...,>50K,3.151338,40.0,0.0,Self-emp-inc,White,United-States,Prof-school,Married-civ-spouse,Husband
3913,Luis Salcedo,"7232 Mcconnell Prairie\r\nEdwardsmouth, MN 55917",-1.019263452,?,f,13.0,35.287238,8.226562,62.914859,6767.0,...,<=50K,184.525920,20.0,0.0,?,White,United-States,Bachelors,Married-civ-spouse,Husband
3914,Malcolm Rotz,"545 Marshall Rapid\r\nEast Stephanieborough, M...",16.1071543,Machine-op-inspct,f,9.0,0.635848,110.484375,11.280522,0.0,...,<=50K,0.829431,40.0,0.0,Private,White,United-States,HS-grad,Divorced,Unmarried
3915,Manuel Dupre,"216 Elliott Squares\r\nLake Breannaborough, MD...",NaN,Sales,f,12.0,2.231021,90.500000,13.174810,0.0,...,>50K,2.298495,38.0,0.0,Self-emp-inc,NaN,NaN,NaN,NaN,NaN
3916,Marcel Ross,33418 Trevino Stravenue Apt. 225\r\nWest Nicho...,11.32787187,Craft-repair,f,10.0,2.259311,99.328125,15.775832,0.0,...,<=50K,1.601171,40.0,0.0,Self-emp-not-inc,White,United-States,Some-college,Divorced,Unmarried
3917,Mark Macklin,4932 Lauren Mission Suite 711\r\nSouth Danielp...,NaN,Adm-clerical,f,13.0,-0.117095,123.773438,21.805846,0.0,...,<=50K,3.596154,40.0,0.0,Private,White,United-States,Bachelors,Never-married,Not-in-family
3918,Mike Murdock,"842 Scott Road\r\nWest Michael, ND 69887",NaN,Sales,f,13.0,-0.265510,136.914062,20.745736,0.0,...,>50K,3.691472,35.0,0.0,Private,Black,United-States,Bachelors,Never-married,Unmarried
3919,Mike Rm,"8317 Sarah Streets Apt. 987\r\nWrighttown, NY ...",12.28357567,Transport-moving,f,5.0,-0.463015,117.078125,14.469198,0.0,...,>50K,1.468227,70.0,0.0,Self-emp-not-inc,White,United-States,9th,Married-civ-spouse,Husband
3920,Paul Ladd,USNS Townsend\r\nFPO AE 97197,6.062392209,Sales,f,9.0,2.179898,94.218750,29.733092,0.0,...,<=50K,5.266722,25.0,0.0,Private,White,United-States,HS-grad,Never-married,Own-child
3921,Randall Mellett,"941 Woods Walks Suite 315\r\nNorth Andrealand,...",6.773794869,Sales,f,10.0,-0.104047,127.546875,25.401128,0.0,...,<=50K,4.233278,45.0,0.0,Private,White,United-States,Some-college,Never-married,Not-in-family
3922,Raymond Goode,"0705 Heather Mountain\r\nFloresmouth, FL 91113",8.074870162,Craft_repair,f,9.0,1.290224,89.437500,18.902544,0.0,...,<=50K,2.625418,32.0,0.0,Self-emp-not-inc,White,United-States,HS-grad,Married-civ-spouse,Husband
3923,Robert Lackey,"94782 Ortega Summit\r\nNew Andrewmouth, MN 99751",8.466196457999999,Other-service,f,9.0,0.492993,NaN,17.515368,0.0,...,<=50K,2.780936,25.0,0.0,Private,White,United-States,HS-grad,Never-married,Other-relative
3924,Russell Coleman,"PSC 1977, Box 7638\r\nAPO AE 29246",0.48443973,Sales,f,13.0,13.105819,17.023438,66.372428,0.0,...,<=50K,95.912207,40.0,0.0,Private,White,United-States,Bachelors,Never-married,Not-in-family
3925,Salvador Donnell,"287 Jessica Springs Apt. 923\r\nSantanaton, ND...",7.151723994,Prof-specialty,FALSE,14.0,0.108239,115.875000,22.170373,0.0,...,>50K,3.521739,42.0,0.0,Private,White,United-States,Masters,Married-civ-spouse,Husband
3926,Steven Jacobs,"84245 Williamson Trail\r\nEast Pamelaside, AL ...",6.633057813,Prof-specialty,f,14.0,1.477925,88.710938,25.308950,0.0,...,<=50K,4.444816,50.0,0.0,State-gov,White,United-States,Masters,Married-civ-spouse,Husband
3927,Tim Price,"4811 Raymond Locks Suite 069\r\nEast Michael, ...",15.36988913,Prof-specialty,t,13.0,-0.191658,125.625000,11.701942,0.0,...,>50K,1.147993,40.0,0.0,Private,White,United-States,Bachelors,Never-married,Not-in-family
3928,Virgil Selman,66909 Frederick Path Apt. 504\r\nPort Jennifer...,NaN,Sales,f,7.0,-0.025640,111.601562,10.809350,0.0,...,<=50K,1.607860,15.0,0.0,Private,White,United-States,11th,Never-married,Own-child
3929,William Glover,"655 Cody River Suite 554\r\nNorth Colton, DC 2...",12.39898059,Sales,f,9.0,-0.172403,138.429688,12.075740,0.0,...,<=50K,1.458194,40.0,0.0,NaN,White,United-States,HS-grad,Married-civ-spouse,Husband
3930,William Hicks,"66744 Tiffany Shores Apt. 950\r\nNew Timothy, ...",2.45648463,Prof-specialty,f,14.0,31.058851,33.226562,57.705184,0.0,...,<=50K,26.705686,40.0,0.0,Federal-gov,White,United-States,Masters,Married-civ-spouse,Husband
3931,William Joecks,"089 Sherry Hollow Suite 058\r\nBrianberg, CT 0...",??,Other-service,f,7.0,-0.220297,117.601562,83.396249,0.0,...,<=50K,79.782609,15.0,0.0,Private,White,United-States,11th,Never-married,Own-child
3932,William Stone,"535 Cabrera Wall Apt. 927\r\nEast David, TX 70904",NaN,Adm-clerical,f,9.0,-0.391453,118.609375,31.452809,0.0,...,<=50K,6.880435,35.0,0.0,Local-gov,Black,United-States,HS-grad,Divorced,Unmarried

In [24]:
sortedO = dataO.sort_values('name')
sortedP = dataP.sort_values('name')

In [25]:
addressO =sortedO['address']
addressP =sortedP['address']

In [26]:
np.array_equal(addressO, addressP)

True

Keďže aj adresy pri menách sú rovnaké tak je jasné, že sa jedna o tie isté osoby a datasety môžeme spojiť na základde mená.

In [27]:
replaced = dataO.replace(to_replace=r'^[0-9,\-].*[0-9]$',value='number',regex=True)
replaced.select_dtypes(include='object')

,name,address,kurtosis_oxygen,occupation,pregnant,income,workclass,ethn,state,edu,status,fam_memb
0,Daniel Love,"126 Ramirez Roads\r\nNew Jayville, IL 18861",number,Sales,f,>50K,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
1,Roy Paradis,"01168 Stark Pine Apt. 583\r\nDavidville, IN 32044",number,Craft-repair,f,<=50K,Self-emp-not-inc,White,United-States,HS-grad,Married-civ-spouse,Husband
2,Charles Chen,"09482 Horne Lakes Apt. 373\r\nEast Brian, TN 2...",number,Handlers-cleaners,f,<=50K,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
3,Chester Holmes,"720 Harris Turnpike Suite 732\r\nEast Sierra, ...",??,Sales,f,>50K,Private,White,United-States,Some-college,Married-civ-spouse,Husband
4,James Ayala,Unit 3230 Box 9523\r\nDPO AA 55810,NaN,Transport-moving,f,<=50K,Private,Amer-Indian-Eskimo,United-States,HS-grad,Married-civ-spouse,Husband
5,Todd Flanagan,"2167 Wells Shoals Apt. 264\r\nEast Brianshire,...",number,?,f,<=50K,?,White,United-States,HS-grad,Married-civ-spouse,Own-child
6,James Huffman,"535 Michael Squares\r\nNorth Sara, ID 61368",number,Sales,f,<=50K,Private,White,United-States,Some-college,Divorced,Not-in-family
7,Gary Prentice,"055 Nolan Club\r\nWest Bryanton, UT 15308",number,?,f,<=50K,?,White,United-States,Assoc-acdm,Divorced,Unmarried
8,Rodger Riis,7719 Frances Drives Apt. 525\r\nWest Brandonst...,number,Sales,f,<=50K,Self-emp-inc,White,United-States,Some-college,Never-married,Own-child
9,Robert Cabiness,"70838 Robbins Camp Suite 853\r\nJacobville, SC...",number,Sales,f,<=50K,Private,White,United-States,HS-grad,Never-married,Own-child
10,John Brehmer,"019 Donna Mountains\r\nAlyssaside, NC 78687",number,Adm-clerical,f,<=50K,Federal-gov,Black,United-States,HS-grad,Separated,Unmarried
11,William West,"692 Tiffany Cape Suite 776\r\nNew Stacey, OK 9...",number,Exec-managerial,f,>50K,Private,White,United-States,Some-college,Married-civ-spouse,Husband
12,Thomas Rathburn,"708 Rodgers Streets Suite 909\r\nVanessamouth,...",number,Craft-repair,f,<=50K,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
13,Steven Welch,4017 Christopher Fort Suite 454\r\nHurleyville...,number,Craft-repair,f,<=50K,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
14,Leon Fleming,"2351 Brian Route Suite 878\r\nPort Richard, SC...",number,Craft-repair,f,>50K,Private,White,United-States,Some-college,Divorced,Not-in-family
15,Jake Pearce,"1633 Sanders Club\r\nSouth Timothymouth, LA 30038",number,Farming-fishing,f,<=50K,State-gov,White,United-States,Some-college,Never-married,Own-child
16,Carl Nelson,"680 Higgins Square\r\nSharonborough, NJ 01147",number,Other-service,f,<=50K,Private,White,United-States,Some-college,Married-civ-spouse,Husband
17,Brian Murphrey,"7682 Cantu Glen\r\nMonroebury, NH 02629",number,Handlers-cleaners,f,<=50K,Private,White,United-States,HS-grad,Never-married,Not-in-family
18,Brian Orozco,"699 Powell Gardens Apt. 171\r\nSloanland, HI 6...",number,Prof-specialty,F,<=50K,Private,White,United-States,Bachelors,Divorced,Not-in-family
19,Julian Davis,75930 Jonathan Passage Suite 688\r\nPort Jamie...,number,Other-service,f,<=50K,Private,White,United-States,Some-college,Married-civ-spouse,Husband
20,John Davenport,802 Christian Course Apt. 645\r\nPort Dominiqu...,number,Sales,f,<=50K,Private,White,United-States,HS-grad,Married-civ-spouse,Wife
21,Oscar Reynolds,"776 Guerrero Lock\r\nLake Erin, NY 53271",number,Tech-support,f,>50K,Private,Asian-Pac-Islander,India,Bachelors,Married-civ-spouse,Husband
22,Louis Stallworth,"476 Kevin Tunnel\r\nJenniferton, VT 33302",number,Craft-repair,f,<=50K,Private,White,United-States,HS-grad,Divorced,Own-child
23,Harold Hiles,"40820 Susan Shore\r\nCoryville, KS 28888",number,Craft-repair,f,<=50K,Self-emp-not-inc,White,United-States,11th,Married-civ-spouse,Husband
24,David Lopez,"420 Jensen Place\r\nPort Kyletown, KS 65788",number,Prof-specialty,f,<=50K,Private,White,United-States,Some-college,Divorced,Unmarried
25,Kenneth Weatherholt,6644 Marshall Mountains Suite 928\r\nWest Susa...,number,Exec-managerial,FALSE,<=50K,Federal-gov,Black,United-States,HS-grad,Separated,Not-in-family
26,Corey Rose,"48053 Jeremiah Estate\r\nJeremychester, TN 50588",number,Adm-clerical,t,<=50K,Private,Black,United-States,Some-college,Divorced,Unmarried
27,Arthur Crandall,806 Matthews River Suite 584\r\nPort Heidiside...,number,Exec-managerial,f,>50K,Private,White,United-States,Assoc-voc,Divorced,Not-in-family
28,Jesse Simpson,"6825 Lopez Crest Suite 574\r\nLake Sarah, CO 6...",number,Craft-repair,f,<=50K,Private,White,United-States,HS-grad,Never-married,Not-in-family
29,Rene Kershner,"1010 Miles Shore Suite 346\r\nWest Edward, NH ...",number,Sales,f,<=50K,Private,White,United-States,HS-grad,Married-civ-spouse,Husband
...,...,...,...,...,...,...,...,...,...,...,...,...
3903,Joseph Palumbo,"14921 Johnson Stravenue\r\nNorth David, KS 12153",number,Prof-specialty,FALSE,>50K,Local-gov,White,United-States,Masters,Married-civ-spouse,Husband
3904,Joseph Perez,"023 Cook Bypass Apt. 625\r\nNorth Anna, FL 05626",number,Machine_op_inspct,f,<=50K,Private,Asian-Pac-Islander,Philippines,Some-college,Married-civ-spouse,Husband
3905,Joseph Williams,"6558 Smith Park Apt. 719\r\nLake Johnmouth, DE...",number,Craft-repair,F,>50K,Private,Black,United-States,Some-college,Married-civ-spouse,Husband
3906,Juan Thurber,"655 Rosales Camp Suite 191\r\nDavisview, WV 49205",number,Prof-specialty,f,>50K,Federal-gov,White,?,Masters,Married-civ-spouse,Husband
3907,Kenneth Burr,"61596 Danielle Trafficway\r\nSouth Ryan, ND 49582",NaN,Prof-specialty,f,>50K,Self-emp-not-inc,White,United-States,Masters,Married-civ-spouse,Husband
3908,Kenneth Zamora,"9086 Becker Streets\r\nNew Michaelbury, MA 54353",number,Transport-moving,f,>50K,Private,White,United-States,HS-grad,Never-married,Not-in-family
3909,Kevin Bell,"793 Erika Springs Suite 802\r\nLake Donnaview,...",number,Adm_clerical,f,<=50K,NaN,White,United-States,HS-grad,Never-married,Own-child
3910,Leslie Pack,"77641 Brian Camp\r\nSouth Amberville, IA 89230",number,Machine-op-inspct,f,<=50K,Private,White,United-States,12th,Never-married,Not-in-family
3911,Lonnie Fuhrman,"77622 Bright Station\r\nMorrismouth, MO 52269",NaN,Other-service,f,<=50K,Private,White,United-States,HS-grad,Never-married,Other-relative
3912,Louis Lochrico,"358 Reed Springs\r\nEast Stevenport, NC 86309",number,Prof-specialty,f,>50K,Self-emp-inc,White,United-States,Prof-school,Married-civ-spouse,Husband
3913,Luis Salcedo,"7232 Mcconnell Prairie\r\nEdwardsmouth, MN 55917",number,?,f,<=50K,?,White,United-States,Bachelors,Married-civ-spouse,Husband
3914,Malcolm Rotz,"545 Marshall Rapid\r\nEast Stephanieborough, M...",number,Machine-op-inspct,f,<=50K,Private,White,United-States,HS-grad,Divorced,Unmarried
3915,Manuel Dupre,"216 Elliott Squares\r\nLake Breannaborough, MD...",NaN,Sales,f,>50K,Self-emp-inc,NaN,NaN,NaN,NaN,NaN
3916,Marcel Ross,33418 Trevino Stravenue Apt. 225\r\nWest Nicho...,number,Craft-repair,f,<=50K,Self-emp-not-inc,White,United-States,Some-college,Divorced,Unmarried
3917,Mark Macklin,4932 Lauren Mission Suite 711\r\nSouth Danielp...,NaN,Adm-clerical,f,<=50K,Private,White,United-States,Bachelors,Never-married,Not-in-family
3918,Mike Murdock,"842 Scott Road\r\nWest Michael, ND 69887",NaN,Sales,f,>50K,Private,Black,United-States,Bachelors,Never-married,Unmarried
3919,Mike Rm,"8317 Sarah Streets Apt. 987\r\nWrighttown, NY ...",number,Transport-moving,f,>50K,Self-emp-not-inc,White,United-States,9th,Married-civ-spouse,Husband
3920,Paul Ladd,USNS Townsend\r\nFPO AE 97197,number,Sales,f,<=50K,Private,White,United-States,HS-grad,Never-married,Own-child
3921,Randall Mellett,"941 Woods Walks Suite 315\r\nNorth Andrealand,...",number,Sales,f,<=50K,Private,White,United-States,Some-college,Never-married,Not-in-family
3922,Raymond Goode,"0705 Heather Mountain\r\nFloresmouth, FL 91113",number,Craft_repair,f,<=50K,Self-emp-not-inc,White,United-States,HS-grad,Married-civ-spouse,Husband
3923,Robert Lackey,"94782 Ortega Summit\r\nNew Andrewmouth, MN 99751",number,Other-service,f,<=50K,Private,White,United-States,HS-grad,Never-married,Other-relative
3924,Russell Coleman,"PSC 1977, Box 7638\r\nAPO AE 29246",number,Sales,f,<=50K,Private,White,United-States,Bachelors,Never-married,Not-in-family
3925,Salvador Donnell,"287 Jessica Springs Apt. 923\r\nSantanaton, ND...",number,Prof-specialty,FALSE,>50K,Private,White,United-States,Masters,Married-civ-spouse,Husband
3926,Steven Jacobs,"84245 Williamson Trail\r\nEast Pamelaside, AL ...",number,Prof-specialty,f,<=50K,State-gov,White,United-States,Masters,Married-civ-spouse,Husband
3927,Tim Price,"4811 Raymond Locks Suite 069\r\nEast Michael, ...",number,Prof-specialty,t,>50K,Private,White,United-States,Bachelors,Never-married,Not-in-family
3928,Virgil Selman,66909 Frederick Path Apt. 504\r\nPort Jennifer...,NaN,Sales,f,<=50K,Private,White,United-States,11th,Never-married,Own-child
3929,William Glover,"655 Cody River Suite 554\r\nNorth Colton, DC 2...",number,Sales,f,<=50K,NaN,White,United-States,HS-grad,Married-civ-spouse,Husband
3930,William Hicks,"66744 Tiffany Shores Apt. 950\r\nNew Timothy, ...",number,Prof-specialty,f,<=50K,Federal-gov,White,United-States,Masters,Married-civ-spouse,Husband
3931,William Joecks,"089 Sherry Hollow Suite 058\r\nBrianberg, CT 0...",??,Other-service,f,<=50K,Private,White,United-States,11th,Never-married,Own-child
3932,William Stone,"535 Cabrera Wall Apt. 927\r\nEast David, TX 70904",NaN,Adm-clerical,f,<=50K,Local-gov,Black,United-States,HS-grad,Divorced,Unmarried

In [28]:
replaced['kurtosis_oxygen'].unique()

array(['number', '??', nan], dtype=object)

In [29]:
replaced['occupation'].unique()

array([' Sales', ' Craft-repair', ' Handlers-cleaners',
       ' Transport-moving', ' ?', ' Adm-clerical', ' Exec-managerial',
       ' Farming-fishing', ' Other-service', ' Prof-specialty',
       ' Tech-support', ' Machine-op-inspct', ' Exec_managerial',
       ' Other_service', ' Prof_specialty', ' Protective-serv',
       ' Craft_repair', ' Protective_serv', ' Adm_clerical',
       ' Machine_op_inspct', ' Farming_fishing', ' Priv-house-serv',
       ' Transport_moving', ' Handlers_cleaners', ' Priv_house_serv',
       ' Tech_support', ' Armed-Forces'], dtype=object)

In [30]:
replaced['pregnant'].unique()

array(['f', 'F', 'FALSE', 't', 'TRUE', 'T'], dtype=object)

In [31]:
replaced['education-num'].unique()

array([ 9., 10., 12., 13.,  7., 11., 14., 16.,  8.,  6.,  3., 15.,  4.,
        5.,  2.,  1.])

In [32]:
replaced['edu'].unique()

array(['HS-grad ', 'Some-college ', 'Assoc-acdm ', 'Bachelors ', '11th ',
       'Assoc-voc ', 'Masters ', 'Doctorate ', '12th ', '10th ',
       '5th-6th ', 'Prof-school ', '7th-8th ', '9th ', '1st-4th ',
       'Preschool ', nan], dtype=object)

In [33]:
replaced['income'].unique()

array([' >50K', ' <=50K', nan], dtype=object)

In [34]:
replaced['workclass'].unique()

array([' Private', ' Self-emp-not-inc', ' ?', ' Self-emp-inc',
       ' Federal-gov', ' State-gov', ' Local-gov', ' Without-pay', nan],
      dtype=object)

In [35]:
replaced['ethn'].unique()

array(['White', 'Amer-Indian-Eskimo', 'Black', 'Asian-Pac-Islander',
       'Other', nan], dtype=object)

In [36]:
replaced['state'].unique()

array(['United-States', 'India', 'Thailand', 'Puerto-Rico', 'Philippines',
       'Cuba', '?', 'China', 'Columbia', 'Canada', 'Poland', 'Mexico',
       'Vietnam', 'El-Salvador', 'Jamaica', 'Japan', 'Yugoslavia',
       'Italy', 'Germany', 'Guatemala', 'Ecuador', 'Hungary', 'Ireland',
       'Taiwan', 'England', 'France', 'Peru', 'Portugal', 'South',
       'Trinadad&Tobago', 'Dominican-Republic', 'Iran', 'Cambodia',
       'Outlying-US(Guam-USVI-etc)', 'Haiti', 'Scotland', 'Nicaragua',
       'Hong', 'Holand-Netherlands', 'Greece', nan], dtype=object)

In [37]:
replaced['status'].unique()

array([' Married-civ-spouse', ' Divorced', ' Never-married', ' Separated',
       ' Widowed', ' Married-spouse-absent', ' Married-AF-spouse', nan],
      dtype=object)

In [38]:
replaced['fam_memb'].unique()

array(['Husband', 'Own-child', 'Not-in-family', 'Unmarried', 'Wife',
       'Other-relative', nan], dtype=object)

Nahradením čisel a vypísaním unikátnych hodnôt sme zistili, že prázdne hodnoty sú označené buď dvoma, jedným otáznikom alebo slovom nan. Tieto hodnoty nahradíme jednotným np.nan. A taktiež prevedieme zjednotenie totožných gramatický rozdielných hodnôt, o ktorých sme vedeli už z analýzy.

In [39]:
correctValuesO(dataO)

In [40]:
dataO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3933 entries, 0 to 3932
Data columns (total 25 columns):
name                3933 non-null object
address             3933 non-null object
kurtosis_oxygen     3539 non-null object
occupation          3733 non-null object
pregnant            3933 non-null object
education-num       3933 non-null float64
skewness_glucose    3933 non-null float64
mean_glucose        3539 non-null float64
std_oxygen          3933 non-null float64
capital-gain        3933 non-null float64
skewness_oxygen     3933 non-null float64
kurtosis_glucose    3933 non-null float64
fnlwgt              3933 non-null float64
class               3933 non-null float64
std_glucose         3932 non-null float64
income              3932 non-null object
mean_oxygen         3933 non-null float64
hours-per-week      3932 non-null float64
capital-loss        3933 non-null float64
workclass           3731 non-null object
ethn                3932 non-null object
state               3857 non-null object
edu                 3932 non-null object
status              3932 non-null object
fam_memb            3932 non-null object
dtypes: float64(13), object(12)
memory usage: 768.2+ KB

In [41]:
dataO['pregnant'].unique()

array(['f', 't'], dtype=object)

In [42]:
replaced = dataP.replace(to_replace = r'[0-9]', value = 'x', regex = True)

In [43]:
replaced["date_of_birth"].unique()

array(['xxxx-xx-xx', 'xx-xx-xx', 'xx/xx/xxxx', 'xxxx-xx-xx xx:xx:xx',
       'xxxx-xx-xx xx xx xx', 'xxxx/xx/xx'], dtype=object)

xx/xx/xxxx --> dd/mm/yyyy

In [44]:
date = dataP["date_of_birth"][dataP["date_of_birth"].str.match(r'[0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9]')].sort_values(ascending=False).str.split("/", 3, expand = True)

In [45]:
date.max()

0      31.0
1      12.0
2    2005.0
dtype: float64

xxxx/xx/xx --> yyyy/mm/dd

In [46]:
date = dataP["date_of_birth"][dataP["date_of_birth"].str.match(r'[0-9][0-9][0-9][0-9]/[0-9][0-9]/[0-9][0-9]')].sort_values(ascending=False).str.split("/", 3, expand = True)

In [47]:
date.max()

0    2020.0
1      12.0
2      31.0
dtype: float64

xxxx-xx-xx --> yyyy-mm-dd

In [48]:
date = dataP["date_of_birth"][dataP["date_of_birth"].str.match(r'[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]')].sort_values(ascending=False).str.split("-", 3, expand = True)

In [49]:
date.max()

0           2016
1             12
2    31 00:00:00
dtype: object

xx-xx-xx --> yy-mm-dd

In [50]:
date = dataP["date_of_birth"][dataP["date_of_birth"].str.match(r'[0-9][0-9]-[0-9][0-9]-[0-9][0-9]')].sort_values(ascending=False).str.split("-", 3, expand = True)

In [51]:
date.max()

0    96.0
1    12.0
2    31.0
dtype: float64

In [52]:
date[0].unique()

array(['96', '93', '91', '90', '89', '88', '87', '86', '85', '84', '83',
       '82', '81', '80', '79', '78', '77', '76', '75', '74', '73', '72',
       '71', '70', '69', '68', '67', '66', '65', '64', '63', '62', '61',
       '60', '59', '58', '57', '56', '55', '54', '53', '52', '51', '50',
       '49', '48', '47', '42', '39', '29', '03', '00'], dtype=object)

Teraz, keď poznáme všetky formáty dátumu a usporiadanie mesiacov a dní môžeme ich zjednotiť.

In [53]:
correctValuesP(dataP)

C:\Users\adria\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [54]:
replaced = dataP.replace(to_replace = r'[0-9]', value = 'x', regex = True)
replaced['date_of_birth'].unique()

array(['xxxx-xx-xx'], dtype=object)

In [55]:
dataF = fusionDatasets(dataP, dataO)

In [56]:
dataF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3933 entries, 0 to 3932
Data columns (total 26 columns):
age                 3933 non-null int64
sex                 3933 non-null object
date_of_birth       3933 non-null object
kurtosis_oxygen     3539 non-null object
occupation          3733 non-null object
pregnant            3933 non-null object
education-num       3933 non-null float64
skewness_glucose    3933 non-null float64
mean_glucose        3539 non-null float64
std_oxygen          3933 non-null float64
capital-gain        3933 non-null float64
skewness_oxygen     3933 non-null float64
kurtosis_glucose    3933 non-null float64
fnlwgt              3933 non-null float64
class               3933 non-null float64
std_glucose         3932 non-null float64
income              3932 non-null object
mean_oxygen         3933 non-null float64
hours-per-week      3932 non-null float64
capital-loss        3933 non-null float64
workclass           3731 non-null object
ethn                3932 non-null object
state               3857 non-null object
edu                 3932 non-null object
status              3932 non-null object
fam_memb            3932 non-null object
dtypes: float64(13), int64(1), object(12)
memory usage: 829.6+ KB

In [57]:
dataF = dataF.astype({'class':str,"education-num":str,"kurtosis_oxygen":float})
dataF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3933 entries, 0 to 3932
Data columns (total 26 columns):
age                 3933 non-null int64
sex                 3933 non-null object
date_of_birth       3933 non-null object
kurtosis_oxygen     3539 non-null float64
occupation          3733 non-null object
pregnant            3933 non-null object
education-num       3933 non-null object
skewness_glucose    3933 non-null float64
mean_glucose        3539 non-null float64
std_oxygen          3933 non-null float64
capital-gain        3933 non-null float64
skewness_oxygen     3933 non-null float64
kurtosis_glucose    3933 non-null float64
fnlwgt              3933 non-null float64
class               3933 non-null object
std_glucose         3932 non-null float64
income              3932 non-null object
mean_oxygen         3933 non-null float64
hours-per-week      3932 non-null float64
capital-loss        3933 non-null float64
workclass           3731 non-null object
ethn                3932 non-null object
state               3857 non-null object
edu                 3932 non-null object
status              3932 non-null object
fam_memb            3932 non-null object
dtypes: float64(12), int64(1), object(13)
memory usage: 829.6+ KB

Vychýlené hodnoty pri veku poznáme z úvdnej analýzy. A vieme, že majú rozdelenie ako dáta mimo vychýlených hodnôt. Po prezretí vychýlených hodnôt sme zistili, že sú to buď 100 alebo -100 násobky bezných hodnôt. A preto ich takto upravíme.

In [ ]:
correctAge(dataF)

C:\Users\adria\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [ ]:
dataF['age'].unique()

In [ ]:
replaced = dataF[['capital-gain', 'capital-loss']].replace(to_replace=[0.0,99999.0],value = np.nan)
replaced.hist()

Pre tieto dva stlpce nebudeme odstranovat outlierov pretoze by sme prisli o tieto namerane hodnoty.

In [ ]:
detectReplaceOutliers(dataF)

In [ ]:
dataF.describe()

Na stĺpce kde chýba málo hodnôt sme sa rozhodli použit nahradenie nulových hodnôt mediánom, kedže sa tam nachádza aj vek a počet odpracovaných hodín a priemer by bol desatíne číslo.

In [ ]:
impMeanFit(dataF)
imp.statistics_

In [ ]:
setKategNaNtoUnknown(dataF)

In [ ]:
dataF.info()

Z analýzy vieme, že nižšie vykreslené atribúty majú najbližšie k linearnemu grafu pre dané atribúty a preto ich použijeme pri lineárnej regresii.

In [ ]:
sns.pairplot(dataF,y_vars=["skewness_glucose", "kurtosis_glucose"], x_vars="mean_glucose")

In [ ]:
sns.pairplot(dataF,y_vars=["skewness_oxygen", "mean_oxygen"], x_vars=["kurtosis_oxygen"])

In [ ]:
linearFit(dataF)

In [ ]:
linearKurtOx.coef_

In [ ]:
linearMeanGlu.coef_

In [ ]:
pred = linearKurtOx.predict(dataF[["skewness_oxygen","mean_oxygen"]])

In [ ]:
plt.scatter(dataF["skewness_oxygen"], dataF["kurtosis_oxygen"],  color='gray')
plt.plot(dataF["skewness_oxygen"], pred, color='red', linewidth=2)
plt.show()

In [ ]:
predG = linearMeanGlu.predict(dataF[["skewness_glucose", "kurtosis_glucose"]])

In [ ]:
plt.scatter(dataF["kurtosis_glucose"], dataF["mean_glucose"],  color='gray')
plt.plot(dataF["kurtosis_glucose"], predG, color='red', linewidth=2)
plt.show()

In [ ]:
linearTransform(dataF)

In [ ]:
dataF.info()

In [ ]:
dataF.describe()

In [ ]:
dataF.describe(exclude=np.number)

<h2>TEST</h2>

In [ ]:
dataPer = pd.read_csv("personal_train.csv", index_col=0)
dataOth = pd.read_csv("other_train.csv", index_col=0)

In [ ]:
dataFin = finalTransform(dataPer,dataOth)

In [ ]:
dataFin.info()

In [ ]:
dataFin.describe()

<h2> Záver </h2>

Výsledkom predpracovania sú dve funkcie:<br>
    finalFitAndTransform(dataP,dataO), ktorá sa spúšťa nad trenovacími dátami, kde upraví hodnoty, zjednoti datasety, upraví outlierov a doplní chýbajúce hodnoty.<br>
    finalTransform(dataP,dataO), ktorá sa spúšťa po predchadzajúcej ale nad testovacými dátami.<br>
    Obydve funkcie vracajú predspracovaný dataset.